trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

jobs:
- template: azure-pipeline-TestAndBuild.yml  # Template reference
  parameters:
    RuleAppName: MultiplicationApp
