
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

pool:
  vmImage: 'windows-2019'

variables:
  RuleAppName: MultiplicationApp
  RuleAppLocation: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  TestSuiteLocation: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName)_Full.testsuite

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'InRuleLicense.xml'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-ExecuteTests'
    Contents: '**'
    TargetFolder: '$(Agent.TempDirectory)'
    OverWrite: true
- script: |
    echo Loading Rule App from $(RuleAppLocation)
    echo Loading Test Suite from  $(TestSuiteLocation)
    .\ExecuteTests.exe  -RuleAppPath:" $(RuleAppLocation)" -TestSuitePath:" $(TestSuiteLocation)"
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Run Tests on $(RuleAppName) Rule App'
  workingDirectory: $(Agent.TempDirectory)
