
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

pool:
  vmImage: 'windows-2019'

variables:
  - group: Credentials
  - name: RuleAppName
    value: MultiplicationApp
  - name: RuleAppLocation
    value: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  - name: TestSuiteLocation
    value: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName)_Full.testsuite
  - name: irJsOutputLocation
    value: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName).min.js

jobs:
- job: Test
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'InRuleLicense.xml'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-ExecuteTests'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo Loading Rule App from $(RuleAppLocation)
      echo Loading Test Suite from $(TestSuiteLocation)
      .\ExecuteTests.exe  -RuleAppPath:" $(RuleAppLocation)" -TestSuitePath:" $(TestSuiteLocation)"
    displayName: 'Run Tests on $(RuleAppName) Rule App'
    workingDirectory: $(Agent.TempDirectory)
- job: Package
  dependsOn: Test
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-BuildIrJsRuleApp'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo Compiling Rule App from $(RuleAppLocation) for irJS to $(irJsOutputLocation)
      .\BuildIrJsRuleApp.exe -DistributionKey:$(irDistributionKey) -OutputPath:"$(irJsOutputLocation)" -RuleAppPath:"$(RuleAppLocation)"
    displayName: 'Build $(RuleAppName) irJS Rule App'
    workingDirectory: $(Agent.TempDirectory)