
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

pool:
  vmImage: 'windows-2019'

variables:
  RuleAppName: MultiplicationApp
  RuleAppLocation: $(build.sourcesDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  TestSuiteLocation: $(build.sourcesDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName)_Full.testsuite
  inrule:repository:licensing:licenseFolder: $(Agent.TempDirectory)



steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'InRuleLicense.xml'
- task: FileTransform@1
  inputs:
    folderPath: '$(build.sourcesDirectory)/!(Helper)*'
    enableXmlTransform: true
    fileType: 'xml'
    targetFiles: '*.exe.config'
- script: |
    echo Loading Rule App from $(RuleAppLocation)
    echo Loading Test Suite from  $(TestSuiteLocation)
    .\Helper-ExecuteTests\ExecuteTests.exe  -RuleAppPath:" $(RuleAppLocation)" -TestSuitePath:" $(TestSuiteLocation)"
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Run Tests on $(RuleAppName) Rule App'
  workingDirectory: $(build.sourcesDirectory)
