# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    .\Helper-ExecuteTests\ExecuteTests.exe  -RuleAppPath:"$(build.sourcesDirectory)\RuleApps\MultiplicationApp\MultiplicationApp.ruleappx" -TestSuitePath:"$(build.sourcesDirectory)\RuleApps\MultiplicationApp\MultiplicationApp.ruleappx"
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Run Tests on Multiplication App'
  workingDirectory: $(build.sourcesDirectory)
