
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Helper*

variables:
  RuleAppName: MultiplicationApp
  RuleAppLocation: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  TestSuiteLocation: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)\$(RuleAppName)_Full.testsuite
  irJsOutputLocationPath: $(System.DefaultWorkingDirectory)\RuleApps\$(RuleAppName)
  irJsOutputLocationName: $(RuleAppName).min.js

jobs:
- job: Package
  pool:
    vmImage: 'windows-2019'
  variables:
  - group: Credentials
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-BuildIrJsRuleApp'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo Compiling Rule App from $(RuleAppLocation) for irJS to $(irJsOutputLocation)
      .\BuildIrJsRuleApp.exe -DistributionKey:$(irDistributionKey) -OutputPath:"$(irJsOutputLocationPath)\$(irJsOutputLocationName)" -RuleAppPath:"$(RuleAppLocation)"
    displayName: 'Build $(RuleAppName) irJS Rule App'
    workingDirectory: $(Agent.TempDirectory)
  - powershell: |
      git --version
      git diff
      git add -A
      git diff
      git config user.email autobuild@inrule.com
      git config user.name "Azure Devops"
      Write-Host "git commit with message"
      git commit -a -m "Add/Update Compiled irJS Rule App"
      Write-Host "git push"
      git push