parameters:
  RuleAppName: 'UNSET'
  SourceCatalogName: 'UNSET'
  DestinationCatalogName: 'UNSET'

jobs:
- job: Test_${{ parameters.RuleAppName }}
  pool:
    vmImage: 'windows-2019'
  variables:
  - name: RuleAppName
    value: ${{ parameters.RuleAppName }}
  - name: RuleTestFolder
    value: $(System.DefaultWorkingDirectory)\catalogSourced-TestAndPromote TestSuites\$(RuleAppName)
  - name: SourceCredLibrary
    value: SourceCatCredsFor$(SourceCatalogName)
  - group: $(SourceCredLibrary)
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'InRuleLicense.xml'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-ExecuteTests'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      for %%i in ("$(RuleTestFolder)\*.testsuite") do ( echo Running TestSuitePath:"%%i" )
      for %%i in ("$(RuleTestFolder)\*.testsuite") do ( .\ExecuteTests.exe -TestSuitePath:"%%i" -CatUri:"$(SourceCatalogUri)" -CatUsername:"$(SourceCatalogUsername)" -CatPassword:"$(SourceCatalogPassword)" -CatRuleAppName:"$(RuleAppName)")
    displayName: 'Run Tests on $(RuleAppName) Rule App'
    workingDirectory: $(Agent.TempDirectory)
- job: Promote_${{ parameters.RuleAppName }}
  dependsOn: Test_${{ parameters.RuleAppName }}
  pool:
    vmImage: 'windows-2019'
  variables:
  - name: RuleAppName
    value: ${{ parameters.RuleAppName }}
  - name: SourceCredLibrary
    value: SourceCatCredsFor$(SourceCatalogName)
  - group: $(SourceCredLibrary)
  - name: DestCredLibrary
    value: DestCatCredsFor$(DestinationCatalogName)
  - group: $(DestCredLibrary)
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'InRuleLicense.xml'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-PromoteRuleApp'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo Promoting Rule App from $(SourceCatalogUri) to $(DestinationCatalogUri)
      .\PromoteRuleApp.exe -RuleAppName:"$(RuleAppName)" -Comment:"Publish from command line tool" -SrcCatUri:"$(SourceCatalogUri)" -SrcCatUser:"$(SourceCatalogUsername)" -SrcCatPass:"$(SourceCatalogPassword)" -DestCatUri:"$(DestinationCatalogUri)" -DestCatUser:"$(DestinationCatalogUsername)" -DestCatPass:"$(DestinationCatalogPassword)"
    displayName: 'Promote $(RuleAppName)'
    workingDirectory: $(Agent.TempDirectory)