trigger:
  branches:
    include:
    - master
  paths:
    include:
    - "fileSourced-IrJS-TestAndBuild RuleApps*"

jobs:
- template: "fileSourced-IrJS-TestAndBuild.yml"
  parameters:
    RuleAppName: MultiplicationApp
- template: "fileSourced-IrJS-TestAndBuild.yml"
  parameters:
    RuleAppName: AdditionApp