trigger:
  branches:
    include:
    - master
  paths:
    include:
      - RuleApps*

jobs:
- template: azure-pipeline-TestAndBuild.yml  # Template reference
  parameters:
    RuleAppName: MultiplicationApp
- template: azure-pipeline-TestAndBuild.yml  # Template reference
  parameters:
    RuleAppName: AdditionApp
