parameters:
  RuleAppName: 'UNSET'

jobs:
- job: Test_${{ parameters.RuleAppName }}
  pool:
    vmImage: 'windows-2019'
  variables:
    RuleAppName: ${{ parameters.RuleAppName }}
    RuleFolder: $(System.DefaultWorkingDirectory)\fileSourced-IrJS-TestAndBuild RuleApps\$(RuleAppName)
    RuleAppLocation: $(System.DefaultWorkingDirectory)\fileSourced-IrJS-TestAndBuild RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'InRuleLicense.xml'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-ExecuteTests'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo running for %%i in (dir "$(RuleFolder)\*.testsuite" /b) do ( .\ExecuteTests.exe -RuleAppPath:"$(RuleAppLocation)" -TestSuitePath:"%%i" )
      for %%i in ("$(RuleFolder)\*.testsuite") do ( echo Running TestSuitePath:"%%i" )
      for %%i in ("$(RuleFolder)\*.testsuite") do ( .\ExecuteTests.exe -RuleAppPath:"$(RuleAppLocation)" -TestSuitePath:"%%i" )
    displayName: 'Run Tests on $(RuleAppName) Rule App'
    workingDirectory: $(Agent.TempDirectory)
- job: Package_${{ parameters.RuleAppName }}
  dependsOn: Test_${{ parameters.RuleAppName }}
  pool:
    vmImage: 'windows-2019'
  variables:
  - group: Credentials
  - name: RuleAppName
    value: ${{ parameters.RuleAppName }}
  - name: irJsOutputLocation
    value: $(System.DefaultWorkingDirectory)\fileSourced-IrJS-TestAndBuild RuleApps\$(RuleAppName)\$(RuleAppName).min.js
  - name: RuleAppLocation
    value: $(System.DefaultWorkingDirectory)\fileSourced-IrJS-TestAndBuild RuleApps\$(RuleAppName)\$(RuleAppName).ruleappx
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Helper-BuildIrJsRuleApp'
      Contents: '**'
      TargetFolder: '$(Agent.TempDirectory)'
      OverWrite: true
  - script: |
      echo Compiling Rule App from $(RuleAppLocation) for irJS to $(irJsOutputLocation)
      .\BuildIrJsRuleApp.exe -DistributionKey:$(irDistributionKey) -OutputPath:"$(irJsOutputLocation)" -RuleAppPath:"$(RuleAppLocation)"
    displayName: 'Build $(RuleAppName) irJS Rule App'
    workingDirectory: $(Agent.TempDirectory)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(irJsOutputLocation)"
      artifact: "$(RuleAppName).min.js"