trigger:
  branches:
    include:
    - master
  paths:
    include:
      - "fileSourced-IrJS-TestAndBuild RuleApps*"

jobs:
- template: azure-pipeline-TestAndBuild.yml
  parameters:
    RuleAppName: MultiplicationApp
- template: azure-pipeline-TestAndBuild.yml
  parameters:
    RuleAppName: AdditionApp